### ISSUE TITLE
opencv3 3.1.0 requires numpy 1.11.0 which breaks cx_freeze

### ISSUE THREAD

**Issue by hschokker** [menpo/conda-opencv3#10]
As the title states, when installing opencv3 3.1.0 it requires to update numpy to 1.11.0. This version of numpy gives me errors when using cx_freeze to create an executable under windows 7 64 bit. I am running python 3.4 64 bit (anaconda).

If there is a way to install opencv3 3.0.0 I would be helped.

**Comment by patricksnape** [comment]
Oh - what is the error exactly? The issue is that our automated Windows build are all shared by a single account and only one build can run at a time. Therefore, have huge build matrices that take a long time to build really starts to hurt the other packages we provide as we end up being stuck waiting for other projects to complete. 

Therefore, providing builds for OpenCV for many numpy versions across 3 Python versions becomes prohibitively expensive for the project. You are welcome to build OpenCV yourself using the recipe, or alternatively you could wait for [conda-forge](https://github.com/conda-forge/opencv-feedstock/pull/16) to merge in OpenCV 3 where both numpy 1.10 and 1.11 builds will be provided.

**Comment by hschokker** [comment]
I have to type it by hand since logging in batch doesn't work when I get this error:

Traceback (most recent call last):
File "setup.py", line 2, in <module>
import numpy as np
File "C:\Users\myname\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy__init__.py", line 180, in <module> 
from . import add_newdocs
File "C:\Users\myname\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module> 

..And similar for these:
from numpy.lib import add_newdoc
from .type_check import *
import numpy.core.numeric as _nx
from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

I get this error when I installed opencv3 3.1.0 and had the numpy version updated to 1.11.0. I will next try to downgrade numpy to 1.9.3 which worked for me with opencv3 3.0.0 before. (Probably this won't work)
