### ISSUE TITLE
Build error due to runaway repeated _placehold string in history file

### ISSUE THREAD

**Issue by oulenz** [menpo/conda-opencv3#24]
I tried to build conda-opencv3 on ubuntu as described in the readme, but received the following error:

```
Can't build [...]/conda-opencv3/conda due to environment creation error:
IO error: Couldn't read or write to file. '[...]/anaconda3/conda-bld/opencv3_1489753787890/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/conda-meta/history'.
Can't write the history file [Errno 36] File name too long: [...]
```

(I was trying to build manually because I hoped this might get me OpenCV 3.2 for Python 3.6, although it looked like it was going to build 3.1, which has a critical bug. Any estimate as to when 3.2 will be available for 3.6?)

**Comment by patricksnape** [comment]
No estimate I'm afraid, I have PR open, but as always buildng OpenCV is incredibly time consuming.

**Comment by Yvanou** [comment]
Hi,

I met quite the same issue with an installation on Mac OSX (Yosemite).

`The following NEW packages will be INSTALLED:

    bzip2:      1.0.6-3             
    cmake:      3.6.3-0             
    curl:       7.54.1-0            
    eigen:      3.2.7-0        menpo
    expat:      2.1.0-0             
    hdf5:       1.8.17-2            
    krb5:       1.13.2-0            
    libssh2:    1.8.0-0             
    mkl:        2017.0.3-0          
    ncurses:    5.9-10              
    numpy:      1.13.1-py27_0       
    openssl:    1.0.2l-0            
    pip:        9.0.1-py27_1        
    python:     2.7.13-0            
    readline:   6.2-2               
    setuptools: 27.2.0-py27_0       
    sqlite:     3.13.0-0            
    tbb:        4.3_20141023-0 menpo
    tk:         8.5.18-0            
    wheel:      0.29.0-py27_0       
    xz:         5.2.2-1             
    zlib:       1.2.8-3             

Source cache directory is: /Users/Yvanou/anaconda/conda-bld/src_cache
Found source in cache: opencv-3.1.0.tar.gz
Extracting download
Applying patch: u'/Users/Yvanou/conda-opencv3/conda/no_rpath.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
patching file CMakeLists.txt
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 397 with fuzz 1 (offset 11 lines).
source tree in: /Users/Yvanou/anaconda/conda-bld/opencv3_1500398427894/work
Attempting to finalize metadata for opencv3
INFO:conda_build.metadata:Attempting to finalize metadata for opencv3

Leaving build/test directories:
  Work:	 ../anaconda/conda-bld/work 
  Test:	 ../anaconda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  ../anaconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 
  Build:	source activate  ../anaconda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place 


Traceback (most recent call last):
  File "/Users/Yvanou/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 999, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 500, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 1632, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 647, in finalize_outputs_pass
    permit_unsatisfiable_variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 647, in finalize_outputs_pass
    permit_unsatisfiable_variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 642, in finalize_outputs_pass
    fm = finalize_metadata(m, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 270, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 112, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/Yvanou/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 705, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['tbb']`

Do you know how to fix it ?

**Comment by patricksnape** [comment]
Please use the conda forge package
