### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by omnigeeker** [menpo/conda-opencv3#26]
my system is ubuntu14.04
and i change build.sh as 
-DWITH_FFMPEG=1 

bug build error:

[ 62%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/tvl1flow.cpp.o
[ 62%] Building CXX object modules/photo/CMakeFiles/opencv_photo.dir/opencl_kernels_photo.cpp.o
[ 62%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/opencl_kernels_video.cpp.o
[ 62%] Building CXX object modules/reg/CMakeFiles/opencv_reg.dir/src/mapshift.cpp.o
[ 62%] Building CXX object modules/reg/CMakeFiles/opencv_reg.dir/src/precomp.cpp.o
[ 62%] Built target opencv_imgcodecs
[ 62%] Linking CXX shared library ../../lib/libopencv_reg.so
[ 62%] Built target opencv_reg
[ 62%] Linking CXX shared library ../../lib/libopencv_video.so
[ 62%] Built target opencv_video
[ 62%] Linking CXX shared library ../../lib/libopencv_photo.so
[ 62%] Built target opencv_photo
make: *** [all] 错误 2
Traceback (most recent call last):
  File "/home/jidou/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1502, in build_tree
    config=config)
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1137, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 616, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/jidou/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 612, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "vim ", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/jidou/anaconda3/conda-bld/opencv3_1490333259451/work/opencv-3.1.0/conda_build.sh']' returned non-zero exit status 2.

**Comment by patricksnape** [comment]
I'm afraid I can't debug options that are not set in the default build. You may be better off asking on the opencv bug tracker.
