### ISSUE TITLE
Cannot build Conda on Windows 10

### ISSUE THREAD

**Issue by MFry** [menpo/conda-opencv3#29]
Following the steps on the README to build opencv3, I cannot get pass `conda build conda/`
```
$ conda install conda-build
$ git clone https://github.com/menpo/conda-opencv3
$ cd conda-opencv3
$ conda config --add channels menpo
$ conda build conda/
$ conda install /PATH/TO/OPENCV3/PACKAGE.tar.gz
```
Running `conda 4.3.16` on  `Python 3.6.1 |Anaconda custom (64-bit)| (default, Mar 22 2017, 20:11:04) [MSC v.1900 64 bit (AMD64)] on win32` fails with:

```
(C:\Users\me\Anaconda3\conda-bld\opencv3_1492974554585\_b_env) Noneif errorlevel 1 exit 1
Traceback (most recent call last):
  File "C:\Users\me\Anaconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\build.py", line 1510, in build_tree
    config=config)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\build.py", line 1109, in build
    windows.build(m, build_file, config=config)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\windows.py", line 231, in build
    check_call_env(cmd, cwd=src_dir)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\utils.py", line 620, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\Users\me\Anaconda3\lib\site-packages\conda_build\utils.py", line 616, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\Users\me\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
```

**Comment by MFry** [comment]
Nevermind according to #21 OpenCV3 is not yet built for python3.6.

**Comment by patricksnape** [comment]
Please use the conda-forge opencv
