### ISSUE TITLE
build error in centos7 & ppc64le (IBM powerpc)

### ISSUE THREAD

**Issue by machanic** [menpo/conda-opencv3#30]
When I build it with **ffmpeg** in 72%, log:
```
[ 72%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/local/ffmpeg-3.3.2/include/../lib/libswscale.a(swscale.o): In function `sws_init_swscale':
/home/machen/download2/ffmpeg-3.3.2/libswscale/swscale.c:585:(.text+0x1b00): call to `ff_sws_init_range_convert' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_videoio.so.3.1.0] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
[ 72%] Linking CXX shared library ../../lib/libopencv_surface_matching.so
[ 72%] Built target opencv_surface_matching
[ 72%] Linking CXX shared library ../../lib/libopencv_photo.so
[ 72%] Built target opencv_photo
make: *** [all] Error 2
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1071, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 670, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 666, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/usr/local/anaconda3/conda-bld/opencv3_1500774271914/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by MoonBlvd** [comment]
I met exact same issue but in 69%. Have you figured this out?

**Comment by patricksnape** [comment]
Please use the conda forge package
